package pt.ua.tqs.hw1.endtoend;

import static org.assertj.core.api.Assertions.assertThat;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.annotation.DirtiesContext;

import io.github.bonigarcia.seljup.SeleniumJupiter;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.Alert;
import java.time.Duration;

@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
@ExtendWith(SeleniumJupiter.class)
class StaffTest {

  @LocalServerPort
  private int port;

  @Test
  void staff(FirefoxDriver driver) {
    driver.get("http://localhost:" + port + "/");
    driver.findElement(By.linkText("User inteface")).click();
    driver.findElement(By.id("descriptionInput")).click();
    driver.findElement(By.id("municipalityInput")).click();
    {
      WebElement dropdown = driver.findElement(By.id("municipalityInput"));
      dropdown.findElement(By.xpath("//option[. = 'Albergaria-a-velha']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(4)")).click();
    driver.findElement(By.id("descriptionInput")).click();
    driver.findElement(By.id("descriptionInput")).clear();
    driver.findElement(By.id("descriptionInput")).sendKeys("O meu pedido");
    driver.findElement(By.id("dateInput")).click();
    driver.findElement(By.id("dateInput")).sendKeys("111220251430");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();

    Alert alert = new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.alertIsPresent());
    assertThat(driver.switchTo().alert().getText()).isEqualTo("The request was submitted successfully! Token: 1");
    alert.accept();

    driver.findElement(By.id("descriptionInput")).click();
    driver.findElement(By.id("descriptionInput")).clear();
    driver.findElement(By.id("descriptionInput")).sendKeys("O meu pedido número 2");
    driver.findElement(By.id("municipalityInput")).click();
    driver.findElement(By.id("municipalityInput")).click();
    driver.findElement(By.id("dateInput")).click();
    driver.findElement(By.id("dateInput")).sendKeys("111220251630");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    
    alert = new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.alertIsPresent());
    assertThat(driver.switchTo().alert().getText()).isEqualTo("The request was submitted successfully! Token: 2");
    alert.accept();
    
    driver.findElement(By.id("municipalityInput")).click();
    {
      WebElement dropdown = driver.findElement(By.id("municipalityInput"));
      dropdown.findElement(By.xpath("//option[. = 'Espinho']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(88)")).click();
    driver.findElement(By.id("descriptionInput")).click();
    driver.findElement(By.id("descriptionInput")).clear();
    driver.findElement(By.id("descriptionInput")).sendKeys("O pedido em espinho");
    driver.findElement(By.id("request-form")).click();
    driver.findElement(By.id("dateInput")).click();
    driver.findElement(By.id("dateInput")).click();
    driver.findElement(By.id("dateInput")).click();
    driver.findElement(By.id("dateInput")).sendKeys("111320251630");
    driver.findElement(By.id("dateInput")).sendKeys("111320251530");
    driver.findElement(By.id("dateInput")).sendKeys("111320251512");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    
    alert = new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.alertIsPresent());
    assertThat(driver.switchTo().alert().getText()).isEqualTo("The request was submitted successfully! Token: 3");
    alert.accept();
    
    driver.get("http://localhost:" + port + "/");
    driver.findElement(By.linkText("Staff interface")).click();
    driver.findElement(By.cssSelector("select:nth-child(3)")).click();
    driver.findElement(By.cssSelector("select:nth-child(3)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select:nth-child(3)"));
      dropdown.findElement(By.xpath("//option[. = 'Albergaria-a-velha']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(4)")).click();
    driver.findElement(By.cssSelector("button:nth-child(2) li:nth-child(4)")).click();
    driver.findElement(By.id("new-state")).click();
    driver.findElement(By.cssSelector("#new-state > option:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#update-state-form > button")).click();
    
    alert = new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.alertIsPresent());
    assertThat(driver.switchTo().alert().getText()).isEqualTo("Request 1 successfully updated to state \"ASSIGNED\".");
    alert.accept();
    
    driver.findElement(By.id("new-state")).click();
    {
      Select select = new Select(driver.findElement(By.id("new-state")));
      select.selectByVisibleText("Start");
    }
    driver.findElement(By.cssSelector("#new-state > option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#update-state-form > button")).click();
    
    alert = new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.alertIsPresent());
    assertThat(driver.switchTo().alert().getText()).isEqualTo("Request 1 successfully updated to state \"IN_PROGRESS\".");
    alert.accept();

    driver.findElement(By.id("new-state")).click();
    {
      Select select = new Select(driver.findElement(By.id("new-state")));
      select.selectByVisibleText("Complete");
    }
    driver.findElement(By.cssSelector("#new-state > option:nth-child(3)")).click();
    driver.findElement(By.cssSelector("#update-state-form > button")).click();
    
    alert = new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.alertIsPresent());
    assertThat(driver.switchTo().alert().getText()).isEqualTo("Request 1 successfully updated to state \"DONE\".");
    alert.accept();
    
    {
      WebElement element = driver.findElement(By.cssSelector("button:nth-child(3) li:nth-child(3) > strong"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("button:nth-child(3) li:nth-child(4) > strong"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("button:nth-child(3) > ul")).click();
    driver.findElement(By.id("new-state")).click();
    {
      Select select = new Select(driver.findElement(By.id("new-state")));
      select.selectByVisibleText("Assign");
    }
    driver.findElement(By.cssSelector("#new-state > option:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#update-state-form > button")).click();
    
    alert = new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.alertIsPresent());
    assertThat(driver.switchTo().alert().getText()).isEqualTo("Request 2 successfully updated to state \"ASSIGNED\".");
    alert.accept();
  }
}
