package pt.ua.tqs.hw1.endtoend;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Duration;

import org.openqa.selenium.Alert;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.annotation.DirtiesContext;

import io.github.bonigarcia.seljup.SeleniumJupiter;

import org.openqa.selenium.WebElement;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
@ExtendWith(SeleniumJupiter.class)
class UserTest {
  
  @LocalServerPort
  private int port;


  @Test
  void user(FirefoxDriver driver) {
      driver.manage().timeouts().implicitlyWait(Duration.ofMillis(500));

    driver.get("http://localhost:" + port + "/");
    driver.findElement(By.linkText("User inteface")).click();
    driver.findElement(By.id("descriptionInput")).click();
    driver.findElement(By.id("descriptionInput"))
        .sendKeys("My fridge is not working and I want you to take it out of here, ok?");
    {
      WebElement dropdown = driver.findElement(By.id("municipalityInput"));
      dropdown.findElement(By.xpath("//option[. = 'Seixal']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(237)")).click();
    driver.findElement(By.id("dateInput")).click();
    driver.findElement(By.id("dateInput")).sendKeys("1112202505:04A");
    
    driver.findElement(By.id("request-form")).click();
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();

    Alert alert = new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.alertIsPresent());
    assertThat(driver.switchTo().alert().getText()).isEqualTo("The request was submitted successfully! Token: 1");
    alert.accept();

    driver.findElement(By.id("tokenInput")).click();
    driver.findElement(By.id("tokenInput")).sendKeys("1");
    driver.findElement(By.id("actionSelect")).click();
    driver.findElement(By.cssSelector("#actionSelect > option:nth-child(1)")).click();
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    driver.findElement(By.id("action-response-description")).click();
    assertThat(driver.findElement(By.id("action-response-description")).getText())
        .isEqualTo("Description: My fridge is not working and I want you to take it out of here, ok?");
    driver.findElement(By.id("action-response-municipality")).click();
    assertThat(driver.findElement(By.id("action-response-municipality")).getText()).isEqualTo("Municipality: Seixal");
    driver.findElement(By.id("action-response-state")).click();
    assertThat(driver.findElement(By.id("action-response-state")).getText()).isEqualTo("State: Recieved");
    {
      WebElement dropdown = driver.findElement(By.id("actionSelect"));
      dropdown.findElement(By.xpath("//option[. = 'Cancel']")).click();
    }
    driver.findElement(By.cssSelector("#actionSelect > option:nth-child(3)")).click();
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    driver.findElement(By.id("action-response")).click();
    assertThat(driver.findElement(By.id("action-response")).getText()).isEqualTo("Request with token 1 cancelled.");
    driver.findElement(By.id("actionSelect")).click();
    {
      WebElement dropdown = driver.findElement(By.id("actionSelect"));
      dropdown.findElement(By.xpath("//option[. = 'See status history']")).click();
    }
    driver.findElement(By.cssSelector("#actionSelect > option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    driver.findElement(By.cssSelector("#action-response-states-list > li")).click();
    assertThat(driver.findElement(By.cssSelector("#action-response-states-list > li")).getText())
        .containsSubsequence("Date:", "State: Cancelled");
         
  }
}
